export enum MODAL_INSTANCE_IDS {
  SIDE_DRAWER = 'SIDE_DRAWER',
  GENERIC_ERROR = 'GENERIC_ERROR',
  NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',
  LOG_FILTERS = 'LOG_FILTERS',
  HYDRATED_POST = 'HYDRATED_POST',
}
