export enum MODAL_INSTANCE_IDS {
  SIDE_DRAWER = 'SIDE_DRAWER',
  GENERIC_ERROR = 'GENERIC_ERROR',
  NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',
  LOG_FILTERS = 'LOG_FILTERS',
  MOD_MENU = 'MOD_MENU',
  REPORT_POST = 'REPORT_POST',
  LOG = 'LOG',
  CONFIRM_REMOVE = 'CONFIRM_REMOVE',
}
